name: Selenium Execution Pipeline

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Select Environment"
        required: true
        default: "qa"
        type: choice
        options: [dev, qa, stage, prod]

      browser:
        description: "Select Browser"
        required: true
        default: "chrome"
        type: choice
        options: [chrome, firefox]

      version:
        description: "Java Version"
        required: true
        default: "21"

      threads:
        description: "Parallel Workers"
        required: true
        default: "2"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.version }}
          cache: maven

      - name: Run Tests (Generate Allure Results)
        run: mvn clean test
        env:
          ENV: ${{ inputs.env }}
          BROWSER: ${{ inputs.browser }}
          THREADS: ${{ inputs.threads }}

      - name: Verify Allure Results
        run: ls -R target || true

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Verify Allure HTML Report
        run: ls -R target/site || true

      - name: Prepare Pages Folder
        run: |
          mkdir -p public
          cp -r target/site/allure-maven-plugin/* public/

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy-report:
    needs: run-tests
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

      - name: Show Report URL
        run: echo "https://nanthithasg03-2004.github.io/SeleniumProject/" >> $GITHUB_STEP_SUMMARY